### ISSUE TITLE
events.js:137       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by chqa** [rain1017/memdb#8]
events.js:137
      throw er; // Unhandled 'error' event 

Error: spawn bash ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)

启动服务端出现这个情况

**Comment by hipandayu** [comment]
这个问题解决了吗
